postgres:
   host: "localhost"
   port: "5432"
   database: "keyman"
   username: "postgres"
   password: "postgres"

file:
  path: "/home/quangha/company/golang/export_to_csv/"
  prefixName: "transaction_"

worker:
  numOfWorker: 10

http:
  port: 8090