postgres:
   host: "localhost"
   port: "5432"
   database: "e_wallet"
   username: "hppoc"
   password: "password"

file:
  path: "/home/sunspirit/"
  prefixName: "transaction_"

worker:
  numOfWorker: 10

http:
  port: 8090